version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: d1v2a3s4
      MYSQL_DATABASE: etl_db
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: d1v2a3s4
      MYSQL_DATABASE: etl_db
    volumes:
      - .:/app
    ports:
      - "5000:5000"
